"""initial baseline

Revision ID: 8edd52d34c76
Revises: 
Create Date: 2026-07-17 22:12:59.715900

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8edd52d34c76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=True),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('faa_code', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=datetime.utcnow),
    sa.Column('updated_at', sa.DateTime(), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airports_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_airports_faa_code'), ['faa_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_airports_iata_code'), ['iata_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_airports_icao_code'), ['icao_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_airports_name'), ['name'], unique=False)

    op.create_table('runways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=False),
    sa.Column('length_m', sa.Integer(), nullable=True),
    sa.Column('width_m', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runways_airport_id'), ['airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runways_designation'), ['designation'], unique=False)

    op.create_table('emas_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('runway_id', sa.Integer(), nullable=True),
    sa.Column('runway_end', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('replacement_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('faa_accepted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['runway_id'], ['runways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emas_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emas_installations_airport_id'), ['airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emas_installations_installation_year'), ['installation_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_emas_installations_runway_id'), ['runway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emas_installations_status'), ['status'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('runway_id', sa.Integer(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=150), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('emas_engaged', sa.Boolean(), nullable=False, default=False),
    sa.Column('injuries', sa.String(length=100), nullable=True),
    sa.Column('aircraft_damage', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('official_report_url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['runway_id'], ['runways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_airport_id'), ['airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_emas_engaged'), ['emas_engaged'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_incident_date'), ['incident_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_runway_id'), ['runway_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('runway_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_level', sa.String(length=30), nullable=False),
    sa.Column('planning_year', sa.Integer(), nullable=True),
    sa.Column('procurement_year', sa.Integer(), nullable=True),
    sa.Column('construction_start', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('estimated_total_value_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_emas_value_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('probability_score', sa.Float(), nullable=False, default=5.0),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('likely_supplier', sa.String(length=150), nullable=True),
    sa.Column('supplier_reason', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['runway_id'], ['runways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_airport_id'), ['airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_confidence_level'), ['confidence_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_planning_year'), ['planning_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_probability_score'), ['probability_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_procurement_year'), ['procurement_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_type'), ['project_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_runway_id'), ['runway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_title'), ['title'], unique=False)

    op.create_table('runway_ends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runway_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=False),
    sa.Column('heading', sa.Integer(), nullable=True),
    sa.Column('resa_length_m', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['runway_id'], ['runways.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runway_id', 'designation')
    )
    with op.batch_alter_table('runway_ends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runway_ends_runway_id'), ['runway_id'], unique=False)

    op.create_table('emas_beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runway_end_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('replacement_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('faa_accepted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False, default=True),
    sa.ForeignKeyConstraint(['runway_end_id'], ['runway_ends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emas_beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emas_beds_installation_year'), ['installation_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_emas_beds_runway_end_id'), ['runway_end_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emas_beds_status'), ['status'], unique=False)
        batch_op.create_index('uq_emas_beds_current_runway_end', ['runway_end_id'], unique=True, sqlite_where=sa.text('is_current = 1'))

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('accessed_date', sa.Date(), nullable=True),
    sa.Column('document_reference', sa.String(length=200), nullable=True),
    sa.Column('page_number', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reliability_level', sa.String(length=30), nullable=False, default='official'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_sources_project_id'))

    op.drop_table('sources')
    with op.batch_alter_table('emas_beds', schema=None) as batch_op:
        batch_op.drop_index('uq_emas_beds_current_runway_end', sqlite_where=sa.text('is_current = 1'))
        batch_op.drop_index(batch_op.f('ix_emas_beds_status'))
        batch_op.drop_index(batch_op.f('ix_emas_beds_runway_end_id'))
        batch_op.drop_index(batch_op.f('ix_emas_beds_installation_year'))

    op.drop_table('emas_beds')
    with op.batch_alter_table('runway_ends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runway_ends_runway_id'))

    op.drop_table('runway_ends')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_runway_id'))
        batch_op.drop_index(batch_op.f('ix_projects_project_type'))
        batch_op.drop_index(batch_op.f('ix_projects_procurement_year'))
        batch_op.drop_index(batch_op.f('ix_projects_probability_score'))
        batch_op.drop_index(batch_op.f('ix_projects_planning_year'))
        batch_op.drop_index(batch_op.f('ix_projects_confidence_level'))
        batch_op.drop_index(batch_op.f('ix_projects_airport_id'))

    op.drop_table('projects')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_runway_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_incident_date'))
        batch_op.drop_index(batch_op.f('ix_incidents_emas_engaged'))
        batch_op.drop_index(batch_op.f('ix_incidents_airport_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('emas_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emas_installations_status'))
        batch_op.drop_index(batch_op.f('ix_emas_installations_runway_id'))
        batch_op.drop_index(batch_op.f('ix_emas_installations_installation_year'))
        batch_op.drop_index(batch_op.f('ix_emas_installations_airport_id'))

    op.drop_table('emas_installations')
    with op.batch_alter_table('runways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runways_designation'))
        batch_op.drop_index(batch_op.f('ix_runways_airport_id'))

    op.drop_table('runways')
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airports_name'))
        batch_op.drop_index(batch_op.f('ix_airports_icao_code'))
        batch_op.drop_index(batch_op.f('ix_airports_iata_code'))
        batch_op.drop_index(batch_op.f('ix_airports_faa_code'))
        batch_op.drop_index(batch_op.f('ix_airports_country'))

    op.drop_table('airports')
    # ### end Alembic commands ###
