"""One-off data migration: move Signal.notes content to the new
Signal.source_notes column for every row reviewed and confirmed as sourced
research (as opposed to a personal, unverified annotation - see
app/models/signal.py's docstrings on both fields and
scripts/add_signal_source_notes_column.py, which adds the column itself).

Every row below was read in full (not pattern-matched) and classified by
content, not by which script wrote it - `annotate_signal.py`'s append_note
helper is reused by sourced-research scripts too (e.g.
scripts/update_lex_emas_details.py), so the "[YYYY-MM-DD] ..." prefix alone
doesn't distinguish the two. The classification and the two borderline
cases (12, 66) were shown to and confirmed by the project owner before this
script was written - see the chat record for the full per-row review.
Signal 5 (FTY) was already moved by hand as the first confirmed case and is
deliberately not in this list.

Four groups, all "sourced research":
- PARAPHRASE_OF_LINKED_SOURCE: short descriptive notes with no inline
  citation, but Signal.source_id points at a real Source row (ALP/CIP/
  Authority board agenda/Environmental Assessment/Master Plan) that the
  note text is clearly paraphrasing - the same "notes describe what
  source_id points at" pattern Installation.notes already uses publicly.
- INLINE_CITED_RESEARCH: notes with an inline citation (URL, document name,
  and/or date) to a specific source, sometimes across multiple dated
  entries (e.g. BGM's cross-references to its own AMPU financial-
  feasibility PDF, WLG's own official announcement superseding an earlier
  shareholder-letter source).
- FAA_INCIDENTS_MAP_IMPORT: templated text generated by the FAA EMAS
  Incidents map import, citing that map by name.
- USASPENDING_GRANT_TEXT: verbatim (ALL CAPS) USAspending.gov grant
  description fields, plus any appended IIJA-grant or AMPU cross-reference
  citations.

Safe to re-run: only touches rows where notes is still non-NULL, so a
second run is a no-op for anything already moved.
"""
from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models import Signal

PARAPHRASE_OF_LINKED_SOURCE = (1, 7, 8, 9, 10, 11)

# 12 (MDW) and 66 (CLT) are the two borderline cases confirmed by the
# project owner: 12's only "source" is RW's own internal Watchlist entry
# (thinly sourced, not personal opinion); 66's second paragraph is an
# internal disambiguation note (factual, not personal, just written for a
# future maintainer rather than a reader).
INLINE_CITED_RESEARCH = (2, 3, 4, 6, 12, 64, 65, 66, 67)

FAA_INCIDENTS_MAP_IMPORT = tuple(range(13, 39))  # 13-38

USASPENDING_GRANT_TEXT = tuple(range(39, 64))  # 39-63

SIGNAL_IDS_TO_MOVE = (
    PARAPHRASE_OF_LINKED_SOURCE
    + INLINE_CITED_RESEARCH
    + FAA_INCIDENTS_MAP_IMPORT
    + USASPENDING_GRANT_TEXT
)


def move_notes_to_source_notes(session: Session, signal_ids=SIGNAL_IDS_TO_MOVE) -> list[int]:
    moved: list[int] = []
    signals = session.scalars(select(Signal).where(Signal.id.in_(signal_ids))).all()
    for signal in signals:
        if signal.notes is None:
            continue
        if signal.source_notes:
            raise SystemExit(
                f"Signal {signal.id} already has source_notes set - refusing to overwrite. "
                "Resolve by hand."
            )
        signal.source_notes = signal.notes
        signal.notes = None
        moved.append(signal.id)
    session.commit()
    return moved


def main() -> None:
    with SessionLocal() as session:
        moved = move_notes_to_source_notes(session)
    if moved:
        print(f"Moved notes -> source_notes for {len(moved)} signals: {sorted(moved)}")
    else:
        print("Nothing to do - all listed signals already moved.")


if __name__ == "__main__":
    main()
